IF(OPEN_GL)
    add_definitions(-DOPEN_GL)

    find_package(OpenGL REQUIRED)
    if(NOT OPENGL_FOUND)
        message(FATAL_ERROR "OpenGL not found")
    endif(NOT OPENGL_FOUND)
    list(APPEND GAME_ENGINE_INCLUDE_DIRS ${OPENGL_INCLUDE_DIR})
    list(APPEND GAME_ENGINE_LIBRARY_PATHS ${OPENGL_LIBRARIES})

    # TODO: change to epoxy instead of glew (resolve issues)
    # epoxy works better on other platforms
    find_package(GLEW REQUIRED)
    if(NOT GLEW_FOUND)
        message(FATAL_ERROR "GLEW not found")
    endif(NOT GLEW_FOUND)
    list(APPEND GAME_ENGINE_INCLUDE_DIRS ${GLEW_INCLUDE_DIRS})
    list(APPEND GAME_ENGINE_LIBRARY_PATHS ${GLEW_LIBRARIES})

    #find_package(epoxy REQUIRED)
    #if(NOT EPOXY_FOUND)
    #    message(FATAL_ERROR "EPOXY not found")
    #endif(NOT EPOXY_FOUND)
    #list(APPEND GAME_ENGINE_INCLUDE_DIRS ${epoxy_INCLUDE_DIR})
    #list(APPEND GAME_ENGINE_LIBRARY_PATHS ${epoxy_LIBRARY})

    find_package(GLFW REQUIRED glfw3)
    if(NOT GLFW_FOUND)
        message(FATAL_ERROR "GLFW not found")
    endif(NOT GLFW_FOUND)
    list(APPEND GAME_ENGINE_INCLUDE_DIRS ${GLFW_INCLUDE_DIRS})
    list(APPEND GAME_ENGINE_LIBRARY_PATHS ${GLFW_LIBRARIES})

    find_package(SOIL REQUIRED)
    if (NOT SOIL_FOUND)
    message(FATAL_ERROR "SOIL not found")
    endif(NOT SOIL_FOUND)
    list(APPEND GAME_ENGINE_INCLUDE_DIRS ${SOIL_INCLUDE_DIRS})
    list(APPEND GAME_ENGINE_LIBRARY_PATHS ${SOIL_LIBRARIES})

    #find_package(GLI REQUIRED)
    #if (NOT GLI_FOUND)
    #message(FATAL_ERROR "GLI not found")
    #endif(NOT GLI_FOUND)
    #list(APPEND GAME_ENGINE_INCLUDE_DIRS ${GLI_INCLUDE_DIRS})
    #list(APPEND GAME_ENGINE_LIBRARY_PATHS ${GLI_LIBRARIES})
ENDIF()
