IF(MINGW)
    message(STATUS "MinGW detected, using OpenGL.")
    SET(OPEN_GL TRUE CACHE BOOL "Use OpenGL")
    SET(DIRECT_X FALSE CACHE BOOL "Use OpenGL")
ELSEIF(WIN32)
    message(STATUS "Windows detected, using DirectX.")
    SET(DIRECT_X TRUE CACHE BOOL "Use DirectX")
    SET(OPEN_GL FALSE CACHE BOOL "Use DirectX")
ELSEIF(UNIX)
    message(STATUS "Unix system detected, using OpenGL.")
    SET(OPEN_GL TRUE CACHE BOOL "Use OpenGL")
    SET(DIRECT_X FALSE CACHE BOOL "Use OpenGL")
ELSEIF(APPLE)
    message(STATUS "Apple detected, using OpenGL.")
    SET(OPEN_GL TRUE CACHE BOOL "Use OpenGL")
    SET(DIRECT_X FALSE CACHE BOOL "Use OpenGL")
ENDIF()