IF(MINGW)
    message(STATUS "MinGW detected, using OpenGL.")
    SET(OPEN_GL TRUE CACHE BOOL)
ELSEIF(WIN32)
    message(STATUS "Windows detected, using DirectX.")
    SET(DIRECT_X TRUE CACHE BOOL)
ELSEIF(UNIX)
    message(STATUS "Unix system detected, using OpenGL.")
    SET(OPEN_GL TRUE CACHE BOOL)
ELSEIF(APPLE)
    message(STATUS "Apple detected, using OpenGL.")
    SET(OPEN_GL TRUE CACHE BOOL)
ENDIF()