FOREACH(file ${SRCS_ALL})
    string(REGEX MATCH "OpenGL/.*OpenGL[^\ ]*\.(h|cpp)" out ${file})
    IF(out)
        IF (OPEN_GL)
            list(APPEND GAME_ENGINE_SOURCES ${file})
        ENDIF()
    ELSE()
        string(REGEX MATCH "DirectX/.*DirectX[^\ ]*\.(h|cpp)" out ${file})
        IF(out)
            IF (DIRECT_X)
                list(APPEND GAME_ENGINE_SOURCES ${file})
            ENDIF()
        ELSE()
            list(APPEND GAME_ENGINE_SOURCES ${file})
        ENDIF()
    ENDIF()
ENDFOREACH()